### ISSUE TITLE
Custom Scripts not working for me

### ISSUE THREAD

**Issue by Toukara** [Farigh/pokeclicker-automation-desktop#17]
I have added custom scripts to my Pokeclicker Desktop, but even when enabled, these scripts do not work.

The scripts I used are from the following GitHub repository: [Ephenia Github](https://github.com/Ephenia/Pokeclicker-Scripts)

I did not encounter any errors, and when I tested them with Tampermonkey on the browser, there were no issues (and to quickly answer any silly questions, no, I do not intend to switch to the browser version).

**Comment by roxieraven327** [comment]
i am in the same exact same boat.

**Comment by Farigh** [comment]
Sorry for the late reply, for some reason I did not get notified from issues on this repository ...

If you used the `One-Click Install` link of a script it does indeed not work.

This is because this script checks if it's executed in the desktop app before running : 
https://github.com/Ephenia/Pokeclicker-Scripts/blob/master/additionalvisualsettings.user.js#L407-L409

all you have to do to make it work is to replace those last 3 lines : 
```js
if (!App.isUsingClient || localStorage.getItem(scriptName) === 'true') {
    loadScript();
}
```
with : 
```js
loadScript();
```

It should then work properly : 
![image](https://github.com/Farigh/pokeclicker-automation-desktop/assets/11090416/b9bccddb-2002-41a0-94b5-dfa92a7e9eb2)
